apiVersion: v1
kind: Service
metadata:
  name: iotd-log
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: iotd
    component: log
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotd-log
spec:
  selector:
    matchLabels:
      app: iotd
      component: log
  template:
    metadata:
      labels:
        app: iotd
        component: log
    spec:
      containers:
        - name: api
          image: "{{ .Values.log.image }}"
          ports:
            - containerPort: 80
              name: api

