apiVersion: v1
kind: Service
metadata:
  name: iotd-web
spec:
  ports:
    - port: 8016
      targetPort: web
  selector:
    app: iotd
    component: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotd-web
spec:
  selector:
    matchLabels:
      app: iotd
      component: web
  template:
    metadata:
      labels:
        app: iotd
        component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}"
          ports:
            - containerPort: 80
              name: web