services:
  accesslog:
    image: ch16-access-log:2e
    build:
      context: ./access-log
    ports:
      - "8012:80"
    networks:
      - app-net

  iotd:
    image: ch16-image-of-the-day:2e
    build:
      context: ./image-of-the-day
    ports:
      - "8011:80"
    networks:
      - app-net

  image-gallery:
    image: ch16-image-gallery:2e
    build:
      context: ./image-gallery
    ports:
      - "8010:80"
    depends_on:
      - accesslog
      - iotd
    networks:
      - app-net

networks:
  app-net:
