name: deploy

on:
#  workflow_run:
#    workflows: ["package-release"]
#    types: [completed]
#    branches:
#      - "main"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository_owner }}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master      
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create-cluster
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: ch16
          args: >-
            --agents 1
            -p "8010:8010@agent:0:direct"
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: get-nodes
        run: |
          kubectl config use-context ch16
          kubectl get nodes -o wide