name: package-staging

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches:
      - "main"
  schedule:
    - cron: "0 23 * * 0"  # Every Sunday at 23:00
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master      
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: package
        working-directory: cicd
        run: ./package.ps1
        shell: pwsh
        env: 
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository_owner }}
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_ID: ${{ github.workflow_ref }}
          COMMIT_SHA: ${{ github.sha	}}
    permissions:
      contents: read
      packages: write

# see docs for GitHub context:
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context