name: smoke-test

on:
  workflow_run:
    workflows: ["package"]
    types: [completed]
    branches:
      - "main"
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master      
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: smoke-test
        working-directory: cicd
        run: ./smoke-test.ps1
        shell: pwsh
        env: 
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository_owner }}