name: smoke-test

on:
  workflow_run:
    workflows: ["package"]
    types: [completed]
    branches:
      - "main"
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master      
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: debug
        working-directory: src
        shell: bash
        run: |
          sudo REGISTRY=ghcr.io REPOSITORY=diamol2e DOCKER_BUILD_OS=linux DOCKER_BUILD_CPU=amd64 docker compose  -f docker-compose.yml -f docker-compose-release-tags.yml config
          sudo REGISTRY=ghcr.io REPOSITORY=diamol2e DOCKER_BUILD_OS=linux DOCKER_BUILD_CPU=amd64 docker compose  -f docker-compose.yml -f docker-compose-release-tags.yml up -d
          curl http://localhost:8010
        env: 
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository_owner }}
      - name: smoke-test
        working-directory: cicd
        run: ./smoke-test.ps1 -RunAsAdmin
        shell: pwsh
        env: 
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository_owner }}